scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/RF/baseline/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/RF/baseline+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/baseline+go_terms_TS_10_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/RF/baseline+intersct_ws/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/baseline+intersct_ws_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/RF/baseline+intersct_ws+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold5/baseline+intersct_ws+go_terms_TS_10_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/RF/baseline/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/RF/baseline+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/baseline+go_terms_TS_10_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/RF/baseline+intersct_ws/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/baseline+intersct_ws_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/RF/baseline+intersct_ws+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold4/baseline+intersct_ws+go_terms_TS_10_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/RF/baseline/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/RF/baseline+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/baseline+go_terms_TS_10_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/RF/baseline+intersct_ws/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/baseline+intersct_ws_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/RF/baseline+intersct_ws+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold3/baseline+intersct_ws+go_terms_TS_10_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/RF/baseline/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/RF/baseline+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/baseline+go_terms_TS_10_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/RF/baseline+intersct_ws/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/baseline+intersct_ws_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/RF/baseline+intersct_ws+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold2/baseline+intersct_ws+go_terms_TS_10_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/RF/baseline/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/RF/baseline+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/baseline+go_terms_TS_10_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/RF/baseline+intersct_ws/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/baseline+intersct_ws_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/RF/baseline+intersct_ws+go_terms_TS_10/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top10_stratify_fold1/baseline+intersct_ws+go_terms_TS_10_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/out.txt New_experiments/ml_models_baseline_stratify_fold1/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/RF/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/RF_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/lambda/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/lambda_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/Ridge/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/Ridge_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/SVR/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/SVR_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/Polynomial_Bagging/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/Polynomial_Bagging_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/Linear/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/Linear_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_baseline_stratify_fold1/Gaussian/baseline/out_train160.txt  New_experiments/ml_models_baseline_stratify_fold1/Gaussian_baseline_out_train160.txt


scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/MLP/baseline/out_train160.txt  New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/MLP_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/SGD/baseline/out_train160.txt  New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/SGD_baseline_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/lambda/baseline/out_train160.txt  New_experiments/ml_models_mlp_sgd_lamda_baseline_stratify_fold1/lambda_baseline_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/out.txt New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/RF/baseline+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/baseline+go_terms_TS_30_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/RF/baseline+intersct_ws+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_50_100_stratify_fold1/baseline+intersct_ws+go_terms_TS_30_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold5/RF/baseline+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold5/baseline+go_terms_TS_30_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold5/RF/baseline+intersct_ws+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold5/baseline+intersct_ws+go_terms_TS_30_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold2/RF/baseline+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold2/baseline+go_terms_TS_30_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold2/RF/baseline+intersct_ws+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold2/baseline+intersct_ws+go_terms_TS_30_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold3/RF/baseline+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold3/baseline+go_terms_TS_30_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold3/RF/baseline+intersct_ws+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold3/baseline+intersct_ws+go_terms_TS_30_out_train160.txt

scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold4/RF/baseline+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold4/baseline+go_terms_TS_30_out_train160.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold4/RF/baseline+intersct_ws+go_terms_TS_30/out_train160.txt  New_experiments/baseline_intersct_ws_go_terms_top30_stratify_fold4/baseline+intersct_ws+go_terms_TS_30_out_train160.txt



<<com
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold1/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/RF/baseline/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold1/baseline_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/RF/baseline+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold1/baseline+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/RF/baseline+intersct_ws/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold1/baseline+intersct_ws_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/RF/baseline+intersct_ws+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold1/baseline+intersct_ws+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold2/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/RF/baseline/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold2/baseline_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/RF/baseline+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold2/baseline+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/RF/baseline+intersct_ws/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold2/baseline+intersct_ws_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/RF/baseline+intersct_ws+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold2/baseline+intersct_ws+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold3/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/RF/baseline/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold3/baseline_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/RF/baseline+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold3/baseline+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/RF/baseline+intersct_ws/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold3/baseline+intersct_ws_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/RF/baseline+intersct_ws+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold3/baseline+intersct_ws+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold4/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/RF/baseline/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold4/baseline_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/RF/baseline+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold4/baseline+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/RF/baseline+intersct_ws/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold4/baseline+intersct_ws_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/RF/baseline+intersct_ws+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold4/baseline+intersct_ws+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/out.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold5/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/RF/baseline/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold5/baseline_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/RF/baseline+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold5/baseline+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/RF/baseline+intersct_ws/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold5/baseline+intersct_ws_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/RF/baseline+intersct_ws+go_terms_TS_10/out_train100.txt New_experiments/baseline_intersct_ws_go_terms_top10_fold5/baseline+intersct_ws+go_terms_TS_10_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold1/RF/PRcurve* New_experiments/baseline_intersct_ws_go_terms_top10_fold1/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold2/RF/PRcurve* New_experiments/baseline_intersct_ws_go_terms_top10_fold2/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold3/RF/PRcurve* New_experiments/baseline_intersct_ws_go_terms_top10_fold3/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold4/RF/PRcurve* New_experiments/baseline_intersct_ws_go_terms_top10_fold4/
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/New_experiments/baseline_intersct_ws_go_terms_top10_fold5/RF/PRcurve* New_experiments/baseline_intersct_ws_go_terms_top10_fold5/
com

<<com
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/SVR/out.txt test_run_exps_tune_train_30_2/SVR_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/SGD/out.txt test_run_exps_tune_train_30_2/SGD_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/RF/out.txt test_run_exps_tune_train_30_2/RF_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/Ridge/out.txt test_run_exps_tune_train_30_2/Ridge_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/Polynomial/out.txt test_run_exps_tune_train_30_2/Polynomial_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/Polynomial_Bagging/out.txt test_run_exps_tune_train_30_2/Polynomial_Bagging_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/MLP/out.txt test_run_exps_tune_train_30_2/MLP_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/Gaussian/out.txt test_run_exps_tune_train_30_2/Gaussian_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_2/Linear/out.txt test_run_exps_tune_train_30_2/Linear_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/SVR/out.txt test_run_exps_tune_train_30_3/SVR_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/SGD/out.txt test_run_exps_tune_train_30_3/SGD_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/RF/out.txt test_run_exps_tune_train_30_3/RF_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/Ridge/out.txt test_run_exps_tune_train_30_3/Ridge_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/Polynomial/out.txt test_run_exps_tune_train_30_3/Polynomial_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/Polynomial_Bagging/out.txt test_run_exps_tune_train_30_3/Polynomial_Bagging_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/MLP/out.txt test_run_exps_tune_train_30_3/MLP_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/Gaussian/out.txt test_run_exps_tune_train_30_3/Gaussian_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_train_30_3/Linear/out.txt test_run_exps_tune_train_30_3/Linear_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/SVR/out.txt test_run_exps_tune_4/SVR_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/SGD/out.txt test_run_exps_tune_4/SGD_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/RF/out.txt test_run_exps_tune_4/RF_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/Ridge/out.txt test_run_exps_tune_4/Ridge_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/Polynomial/out.txt test_run_exps_tune_4/Polynomial_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/Polynomial_Bagging/out.txt test_run_exps_tune_4/Polynomial_Bagging_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/MLP/out.txt test_run_exps_tune_4/MLP_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/Gaussian/out.txt test_run_exps_tune_4/Gaussian_out.txt
scp -r sahitil2@timan107.cs.illinois.edu:DeepMutations/test_run_exps_tune_4/Linear/out.txt test_run_exps_tune_4/Linear_out.txt
com

